### Get all the artists
GET http://localhost:3000/api/artists


### POST
# @name createArtist
POST http://localhost:3000/api/artists
Content-Type: application/json

{
    "name": "Indio Solari",
    "age" : 70,
    "records":[1]
}

### ID
@id = {{createArtist.response.body.data.id}}

### Get one artist
GET http://localhost:3000/api/artists/{{id}}

### Update an artist
PUT http://localhost:3000/api/artists/{{id}}
Content-Type: application/json

{
    "records": [1]
}

### Delete an artist
DELETE http://localhost:3000/api/artists/{{id}}


### POST
# @name createArtist2
POST http://localhost:3000/api/artists
Content-Type: application/json

{
    "name": "Lana del Rey",
    "age" : 39,
    "records": [2]
}
